SELECT * FROM TB_EMP;

-- 테이블 생성
-- 성적정보 저장 테이블
CREATE TABLE TBL_SCORE  (
    NAME VARCHAR2 (4) NOT NULL,
    KOR NUMBER(3) NOT NULL CHECK(KOR > 0 AND KOR <= 100),
    ENG NUMBER(3) NOT NULL CHECK(ENG > 0 AND ENG <= 100),
    MATH NUMBER(3) NOT NULL CHECK(MATH > 0 AND MATH <= 100),
    TOTAL NUMBER(3)  NULL,
    AVERAGE NUMBER(5,2),
    GRADE CHAR(1),
    STU_NUM NUMBER(6),
    -- PK 거는 법

    CONSTRAINT PK_STU_NUM
    PRIMARY KEY (STU_NUM)

);

-- 컬럼 추가하기

ALTER TABLE
    TBL_SCORE
ADD (SCI NUMBER(3) NOT NULL );

-- 컬럼 제거하기

ALTER TABLE
    TBL_SCORE
DROP COLUMN SCI;

-- 테이블 복사 (TB_EMP)
-- CTAS

CREATE TABLE TB_EMP_COPY
AS SELECT * FROM TB_EMP;

-- 복사 테이블 조회
SELECT * FROM TB_EMP_COPY;


-- DROP TABLE
DROP TABLE TB_EMP_COPY;

-- TRUNCATE TABLE
-- 구조는 냅두고 내부 데이터만 전체 삭제

TRUNCATE TABLE TB_EMP_COPY;



ALTER TABLE TBL_SCORE
ADD CONSTRAINT PK_STU_NUM
PRIMARY KEY (STU_NUM);

-- 예시테이블
CREATE TABLE GOODS (
    ID NUMBER (6) PRIMARY KEY,
    G_NAME VARCHAR2(10) NOT NULL,
    PRICE NUMBER(10) DEFAULT 1000,
    REG_DATE DATE

);

SELECT  * FROM GOODS;

INSERT INTO GOODS
    (ID, G_NAME,PRICE,REG_DATE)
VALUES (1, '선풍기', '120000', SYSDATE);

INSERT INTO GOODS
    (ID, G_NAME,PRICE,REG_DATE)
VALUES (2,500000, SYSDATE);

INSERT INTO GOODS
    (ID, G_NAME,REG_DATE)
VALUES (2,'달고나', SYSDATE);

INSERT INTO GOODS
(ID, G_NAME,PRICE)
VALUES (3,'후리', 500);

-- 컬럼명 생략시 모든 컬럼에 대해 순서대로 넣어야함.
-- 실무에서 이렇게 사용하면 안됨
INSERT INTO GOODS
VALUES (4,'세탁기', 10000, SYSDATE);

-- INSERT INTO GOODS
-- (ID, G_NAME,PRICE,REG_DATE)
-- VALUES
--     (5,'세탁기', 10000, SYSDATE)
--         (6,'세탁기1', 10000, SYSDATE);
-- --     (7,'세탁기2', 10000, SYSDATE);

SELECT  * FROM GOODS;

-- 수정
UPDATE GOODS
SET G_NAME = '냉장고'
WHERE ID = 3;
UPDATE GOODS
SET G_NAME = '콜라', PRICE = 3000
WHERE ID = 2;
UPDATE GOODS
SET G_NAME = '콜라', PRICE = 9999
;


UPDATE GOODS
SET PRICE = NULL
WHERE ID = 1;

-- 행을 삭제
DELETE FROM GOODS
WHERE ID = 3;



SELECT  * FROM GOODS;


-- 모든 행 삭제
DELETE FROM GOODS;

-- SELECT 조회
SELECT
       CERTI_NM
,   ISSUE_INSTI_NM
,   CERTI_CD
FROM TB_CERTI;

-- 중복제거 DISTINCT
SELECT DISTINCT
       ISSUE_INSTI_NM
FROM TB_CERTI;


-- 모든 컬럼 조회
-- 실무에서는 사용 X

SELECT *
FROM TB_CERTI;

-- 열의 별칭 부여 (ALIAS)
SELECT
      EMP_NM AS "사원",
    ADDR  AS "주소"
FROM TB_EMP;

SELECT
    TE.EMP_NM AS "사원",
    TE.ADDR  AS "주소"
FROM TB_EMP TE;

-- 문자열 연결하기

SELECT
    CERTI_NM || '('|| TB_CERTI.ISSUE_INSTI_NM || ')'
    AS "자격증 정보"
FROM TB_CERTI;



